// This file is auto-generated by Petezah/CppPinvokeGenerator (EgorBo/CppPinvokeGenerator). Do not edit.

using System;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;

namespace TestAPI
{
    public enum MyTestEnum
    {
        One = 0,
        Two = 1,
        Three = 2,
    }
}
